const initialValues = {
  copiaFiniquito: false,
  copiaContratatoTrabajo: false,
  copiaBajaIMSS: false,
  copiaNomina: false,
  formatoFM2FM3: false,
  copiaCheque: false,
  copiaHistorico: false,
  copiaFiel: false,
  copiaDictamenMedico: false,
  analisisClinicos: false,
  copiaActaMatrimonio: false,
  copiaActaNacimiento: false,
  notarialTutores: false,
  formatoST4: false,
  informeMedico: false,
  analisisPatologicos: false,
  actaDefuncion: false,
  copiaCertificadoDefuncion: false,
  copiaIneOficial: false,
  copiaBeneficiaria: false,
  copiaNacimientoBeneficiario: false,
  beneficiariosMenores: false,
  ministerioPublico: false,
  historialClinico: false,
  copiaDenuncia: false,
  copiaActuacionesMinisterio: false,
};

export default initialValues;
