const initialState = {
  aseguradoContratante: {
    nombre: "",
    apellidoPaterno: "",
    apellidoMaterno: "",
    direccionCalleNumero: "",
    cp: "",
    colonia: "",
    delegacionMunicipio: "",
    estadoEntidadFederativa: "",
    nacionalidad: "",
    paisNacimiento: "",
    poliza: "",
    fechaNacimiento: "",
    telefono: "",
    celular: "",
    correoElectronico: "",
    rfc: "",
    fiel: "",
    ciudad: "",
    ocupacion: "",
    numCuenta: "",
    numBoleta: "",
  },
  beneficiario: {
    nombre: "",
    apellidoPaterno: "",
    apellidoMaterno: "",
    direccionCalleNumero: "",
    cp: "",
    colonia: "",
    delegacionMunicipio: "",
    estadoEntidadFederativa: "",
    nacionalidad: "",
    paisNacimiento: "",
    poliza: "",
    fechaNacimiento: "",
    telefono: "",
    celular: "",
    correoElectronico: "",
    rfc: "",
    fiel: "",
    ciudad: "",
    ocupacion: "",
    cuenta: "",
    clabe: "",
    sucursal: "",
    banco: "",
  },
  reclamante: {
    asegurado: "",
    tipoReclamacion: "",
    fechaSiniestro: "",
    idCliente: "",
  },
  cobertura: {
    muerteAccidental: false,
    incapacidadPermanenteAccidente: false,
    reembolsoGastos: false,
    cancer: false,
    infartoMiocardio: false,
    accidenteCerebro: false,
    roboBolso: false,
    dañoAccidentalEquipo: false,
    fraudeCelular: false,
    roboEquipoFijo: false,
    fractura: false,
    hospitalizacion: false,
    cirugia: false,
    gastosFunerarios: false,
    seguroSaldado: false,
    fallecimienEnfermedad: false,
    accidenteVacular: false,
    esclerosisMultiple: false,
    indemnizacionHospitalizacion: false,
    nacimientoHijo: false,
    fallecimientoAccidental: false,
    falecimientoFamiliar: false,
    fallecimientoReciprocoAccid: false,
    invalidezPermanente: false,
    invalidezTemporal: false,
    desempleoInvoluntario: false,
    incapacidadTemporal: false,
    incapacidadPermanente: false,
    infartoDianostico: false,
    robo: false,
    valorDeuda: false,
    fallecimientoReciproco: false,
    muerteReciproca: false,
    desempleo: false,
    muerteAcciRobo: false,
    invalidezReciproca: false,
    incapacidadTemporalCobertura: false,
    incapacidadPermanenteCobertura: false,


  },
};

export default initialState;
